# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# For a detailed guide to building and testing on Android, read the docs:
# https://circleci.com/docs/2.0/language-android/ for more details.
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Use the circleci android orb version that supports OpenJDK17 required by AGP 8.2+ 
  android: circleci/android@2.4.0
  codecov: codecov/codecov@3.2.4

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code:
        gradle-cache-prefix: v1
        build-cache-prefix: v1

      - build-and-unit-test:
        gradle-cache-prefix: v1
        build-cache-prefix: v1
          requires:
            - validate-code

      - functional-test:
        gradle-cache-prefix: v1
        build-cache-prefix: v1
          requires:
            - validate-code
 
jobs:
   validate-code:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      tag: 2022.09.2-node

    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: Check Code Format
          command: make format-check

      - run:
          name: Lint Code
          command: make lint

      - android/save-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      # Store Lint report
      - store_artifacts:
          path: code/edge/build/reports

  build-and-unit-test:
    parameters:
      gradle-cache-prefix:
        type: string
        default: v1
      build-cache-prefix:
        type: string
        default: v1

    # List of available Android Docker images: https://circleci.com/developer/images/image/cimg/android#image-tags
    executor:
      name: android/android-docker
      tag: 2022.09.2-node

    steps:
      - checkout

      - android/restore-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
      - android/restore-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      - run:
          name: build library
          command: |
            make assemble-phone

      - run:
          name: build jitpack library
          command: |
            make publish-maven-local-jitpack

      - store_artifacts:
          path: code/edgeconsent/build/libs

      - run:
          name: Javadoc
          command: make javadoc
      - store_artifacts:
          path: javadoc/build/reports

      - run:
          name: Build
          command: make build

      - run:
          name: Build App
          command: make build-app

      - run:
          name: UnitTests
          command: make unit-test

     # code coverage
     - run:
          name: code coverage
          command: |
            make unit-test-coverage

     - android/save-gradle-cache:
          cache-prefix: << parameters.gradle-cache-prefix >>
     - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>
 
      - codecov/upload:
          file: code/edgeconsent/build/reports/coverage/test/phone/debug/report.xml
          flags: unit-tests

      - store_artifacts:
          path: unit-test/build/reports

      - store_test_results:
          path: unit-test/build/test-results

  functional-test:
    parameters:
    gradle-cache-prefix:
      type: string
      default: v1
    build-cache-prefix:
      type: string
      default: v1

     # list of available Android machine images: https://circleci.com/developer/machine/image/android#image-tags
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2022.09.1

    steps:
      - checkout

      - android/restore-build-cache:
        cache-prefix: << parameters.build-cache-prefix >>
      
      - run:
         name: List available emulator images
         command: sdkmanager --list

      - android/start-emulator-and-run-tests:
          #   It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          #   The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make build
          #   The test command
          test-command: make functional-test

       - android/save-build-cache:
          cache-prefix: << parameters.build-cache-prefix >>

      # code coverage
       - run:
          name: code coverage
          command: |
            make functional-test-coverage
      - codecov/upload:
          file: code/core/build/reports/coverage/androidTest/phone/connected/debug/report.xml
          flags: functional-tests

      - store_artifacts:
          path: functional-test/build/reports

       # On test failures, the step in the Makefile to copy the reports to ci/ is not run, so store test results from build folder instead.
      - store_test_results:
          path: code/edgeconsent/build/outputs/androidTest-results

